### ISSUE TITLE
default addr for network '127.0.0.1' unknown 

### ISSUE THREAD

**Issue by aliwo** [imiric/xk6-sql#10]
Hello, I met across a problem, could you help me?

## My Environment
* Mac os Catalina
* xk6_0.4.5_mac_amd64.tar.gz

## What I did
```
// test.js
import sql from 'k6/x/sql';

const db = sql.open('mysql', 'mysql://root:<password>@127.0.0.1/<database>?charset=UTF8MB4');

export function setup() {

}

export function teardown() {
    db.close();
}

export default function () {
    db.exec('SELECT NOW();');
    let result = sql.query(db, 'SELECT NOW();');
    console.log(result);
}
```

```
./k6 run test.js
```

## What happened

it returns...

```
ERRO[0000] default addr for network '127.0.0.1' unknown
        at go.k6.io/k6/js/common.Bind.func1 (native)
```

## What I want to do
connect to mysql successfully

**Comment by imiric** [comment]
Hi, I just merged #9 which adds a MySQL example.

The issue you're having is because you need to specify the IP in the connection string between parenthesis.

So the following worked for me (tested with Docker):
```javascript
const db = sql.open('mysql', 'root:<password>@(127.0.0.1)/<database>?charset=UTF8MB4');
```
