### ISSUE TITLE
How to compile it under windows 

### ISSUE THREAD

**Issue by sergiutugulschi** [imiric/xk6-sql#3]
Running CGO_ENABLED=1 go run ./cmd/xk6/main.go build master \ --with github.com/imiric/xk6-sql
'CGO_ENABLED' is not recognized as an internal or external command,
operable program or batch file. 

I have installed go, if I run without CGO_ENABLED=1 i'm getting [ERROR] missing flag;

**Comment by dboreham** [comment]
ymmv, but I am using containers on Windows (with Docker Desktop and WSL2 integration) to bypass the Windows build hassles. Example here : https://github.com/dboreham/xk6-sql-container

**Comment by imiric** [comment]
Hi there, apologies for the late response, I missed the GitHub notification for this issue.

I added the Windows instructions in fc5bb4f, since the way environment variables are specified works differently on Windows shells. But I confirmed this approach works on Windows 10.
